Added osu irc client class
MirayaProject/miraya pull request #2
Opened 2022-07-06 20:40 UTC by Gr3g027

The IRC works, whats left to do is picking up the osu link from a chat message and send it.

2022-07-06 21:59 UTC, Sclafus requested changes
Watch out for whitespaces, everything else looks good to me

2022-07-06 21:59 UTC, Sclafus commented on gosumemoryClient.cpp
> +        // qDebug() << "GosumemoryClient: message received from: " << url.toString() << message;
Watch out for whitespaces

2022-07-06 21:59 UTC, Sclafus commented on gosumemoryClient.h
> +    public slots:
My bad, thanks for the correction
But watch out for whitespaces 👀

2022-07-06 21:59 UTC, Sclafus commented on osuircclient.cpp
> +    connect(&socket, &QTcpSocket::connected, this, &OsuIrcClient::onConnected);
This fails the build
I don't know why

2022-07-07 08:59 UTC, Gr3g027 commented on osuircclient.cpp
> +    connect(&socket, &QTcpSocket::connected, this, &OsuIrcClient::onConnected);
It was the pointer variable socket, corrected

2022-07-07 18:32 UTC, Sclafus approved these changes
Looks good to me

2022-07-07 18:33 UTC, merged